version: '3'
services:
  platex:
    build: ./.config/platex/
    container_name: platex
    volumes:
      - .:/workdir
    command: >
      /bin/ash -c "platex -output-directory=out /workdir/main.tex &&
                   platex -output-directory=out /workdir/main.tex &&
                   dvipdfmx ./out/main.dvi"